<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\centralpark.bmp" />
    <None Remove="Resources\Images\citos.bmp" />
    <None Remove="Resources\Images\mobil.bmp" />
    <None Remove="Resources\Images\paskal.bmp" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Images\centralpark.bmp">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Resources\Images\citos.bmp">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Resources\Images\mobil.bmp">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Resources\Images\paskal.bmp">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.17" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.9.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RfidBarcode.Application\RfidBarcode.Application.csproj" />
    <ProjectReference Include="..\RfidBarcode.Domain\RfidBarcode.Domain.csproj" />
    <ProjectReference Include="..\RfidBarcode.Infrastructure\RfidBarcode.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Models\Auth\" />
  </ItemGroup>

</Project>
