// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RfidBarcode.Infrastructure;

#nullable disable

namespace RfidBarcode.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251230024839_003_AccessMenu")]
    partial class _003_AccessMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long?>("ApplicationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("ApplicationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("ApplicationUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.AccessMenu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("AccessMenus");

                    b.HasData(
                        new
                        {
                            Id = "UM",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "User Management",
                            LastUpdateBy = "system",
                            LastUpdateDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "RM",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Role Management",
                            LastUpdateBy = "system",
                            LastUpdateDate = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.DailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PreviousDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("DailyReports");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Gate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Gates");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.GateMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Antenna")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("GateId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("NextLocationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PrevLocationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GateId");

                    b.HasIndex("NextLocationId");

                    b.HasIndex("PrevLocationId");

                    b.ToTable("GateMaps");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Identities.AccessMenuRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AccessMenuId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccessMenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccessMenuRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessMenuId = "UM",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdateBy = "system",
                            LastUpdateDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            AccessMenuId = "RM",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastUpdateBy = "system",
                            LastUpdateDate = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Identities.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Admin Finish",
                            NormalizedName = "ADMIN FINISH"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "QC Finish",
                            NormalizedName = "QC FINISH"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Gudang Kain",
                            NormalizedName = "GUDANG KAIN"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "QC Gudang Kain",
                            NormalizedName = "QC GUDANG KAIN"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Admin Gudang Kain",
                            NormalizedName = "ADMIN GUDANG KAIN"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Gudang Jakarta",
                            NormalizedName = "GUDANG JAKARTA"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Admin Gudang Jakarta",
                            NormalizedName = "ADMIN GUDANG JAKARTA"
                        });
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Identities.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Identities.ApplicationUserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.ImportItemLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ImportItemLogs");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Epc")
                        .HasColumnType("longtext");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext");

                    b.Property<string>("IdentitasBenang")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("InScan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InScanUser")
                        .HasColumnType("longtext");

                    b.Property<long?>("InScanUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InSuratJalanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Inisial")
                        .HasColumnType("longtext");

                    b.Property<string>("K")
                        .HasColumnType("longtext");

                    b.Property<string>("K3l")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Kg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kode")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode1")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode2")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode3")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode4")
                        .HasColumnType("longtext");

                    b.Property<string>("Kp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lebar")
                        .HasColumnType("longtext");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Merk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OutScan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OutScanUser")
                        .HasColumnType("longtext");

                    b.Property<long?>("OutScanUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OutSuratJalanId")
                        .HasColumnType("bigint");

                    b.Property<string>("Oz")
                        .HasColumnType("longtext");

                    b.Property<string>("Point")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("QcFinish")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("QcFinishUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Qr")
                        .HasColumnType("longtext");

                    b.Property<int?>("R")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<long?>("SuratJalanId")
                        .HasColumnType("bigint");

                    b.Property<string>("SusutLusi")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalBuatBarcode")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("TrackingItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Yard")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InSuratJalanId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OutSuratJalanId");

                    b.HasIndex("SuratJalanId");

                    b.HasIndex("TrackingItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.ItemMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("LocationName")
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<long?>("PrevLocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PrevLocationName")
                        .HasColumnType("longtext");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<long?>("TagLocationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PrevLocationId");

                    b.ToTable("ItemMovements");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.ItemPrintLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemPrintLogs");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkipStockOpname")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.StockOpname", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FinalLocationName")
                        .HasColumnType("longtext");

                    b.Property<string>("FinalTrolleyName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TrolleyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("StockOpnames");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.StockOpnameDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FinalLocation")
                        .HasColumnType("longtext");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<long>("StockOpnameId")
                        .HasColumnType("bigint");

                    b.Property<string>("TagId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long?>("TagLocationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockOpnameId");

                    b.HasIndex("TagLocationId");

                    b.ToTable("StockOpnameDetails");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.SuratJalan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ConfirmDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinalizeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode1")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode2")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode3")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode4")
                        .HasColumnType("longtext");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("No")
                        .HasColumnType("longtext");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("SuratJalanName")
                        .HasColumnType("longtext");

                    b.Property<string>("SuratJalanType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SuratJalans");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.SuratJalanType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("SuratJalanTypes");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.TagLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndScanned")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Epc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FinalLocation")
                        .HasColumnType("longtext");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<long?>("PrevLocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartScanned")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("StockOpnameId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PrevLocationId");

                    b.HasIndex("StockOpnameId");

                    b.ToTable("TagLocations");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.TrackingItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EncodeTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EndProcess")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FormId")
                        .HasColumnType("longtext");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext");

                    b.Property<string>("Ib")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ImportTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Inisial")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Kg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kode")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode1")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode2")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode3")
                        .HasColumnType("longtext");

                    b.Property<string>("Kode4")
                        .HasColumnType("longtext");

                    b.Property<string>("Kp")
                        .HasColumnType("longtext");

                    b.Property<string>("LastUpdateBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Lebar")
                        .HasColumnType("double");

                    b.Property<string>("Merk")
                        .HasColumnType("longtext");

                    b.Property<float?>("MeterBBSF")
                        .HasColumnType("float");

                    b.Property<float?>("MeterGreige")
                        .HasColumnType("float");

                    b.Property<float?>("MeterWeaving")
                        .HasColumnType("float");

                    b.Property<string>("NoBeamIndigo")
                        .HasColumnType("longtext");

                    b.Property<string>("Oz")
                        .HasColumnType("longtext");

                    b.Property<string>("Point")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartProcess")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StockOutDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SusutLusi")
                        .HasColumnType("longtext");

                    b.Property<long?>("TrolleyId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeavingMachineNo")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Yard")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TrackingItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.GateMap", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Gate", "Gate")
                        .WithMany("GateMaps")
                        .HasForeignKey("GateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfidBarcode.Domain.Entities.Location", "NextLocation")
                        .WithMany("GateMapNext")
                        .HasForeignKey("NextLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfidBarcode.Domain.Entities.Location", "PrevLocation")
                        .WithMany("GateMapPrev")
                        .HasForeignKey("PrevLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Gate");

                    b.Navigation("NextLocation");

                    b.Navigation("PrevLocation");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Identities.AccessMenuRole", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.AccessMenu", "AccessMenu")
                        .WithMany("AccessMenuRoles")
                        .HasForeignKey("AccessMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessMenu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Identities.ApplicationUserRole", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Item", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.SuratJalan", "InSuratJalan")
                        .WithMany()
                        .HasForeignKey("InSuratJalanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RfidBarcode.Domain.Entities.Location", "Location")
                        .WithMany("Items")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RfidBarcode.Domain.Entities.SuratJalan", "OutSuratJalan")
                        .WithMany()
                        .HasForeignKey("OutSuratJalanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RfidBarcode.Domain.Entities.SuratJalan", null)
                        .WithMany("Items")
                        .HasForeignKey("SuratJalanId");

                    b.HasOne("RfidBarcode.Domain.Entities.TrackingItem", "TrackingItem")
                        .WithMany("Items")
                        .HasForeignKey("TrackingItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InSuratJalan");

                    b.Navigation("Location");

                    b.Navigation("OutSuratJalan");

                    b.Navigation("TrackingItem");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.ItemMovement", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Item", "Item")
                        .WithMany("ItemMovements")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfidBarcode.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RfidBarcode.Domain.Entities.Location", "PrevLocation")
                        .WithMany()
                        .HasForeignKey("PrevLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Item");

                    b.Navigation("Location");

                    b.Navigation("PrevLocation");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.ItemPrintLog", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Item", "Item")
                        .WithMany("ItemPrintLogs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.StockOpname", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.StockOpnameDetail", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Item", "Item")
                        .WithMany("StockOpnameDetails")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RfidBarcode.Domain.Entities.StockOpname", "StockOpname")
                        .WithMany("StockOpnameDetails")
                        .HasForeignKey("StockOpnameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RfidBarcode.Domain.Entities.TagLocation", "TagLocation")
                        .WithMany()
                        .HasForeignKey("TagLocationId");

                    b.Navigation("Item");

                    b.Navigation("StockOpname");

                    b.Navigation("TagLocation");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.SuratJalan", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Identities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.TagLocation", b =>
                {
                    b.HasOne("RfidBarcode.Domain.Entities.Item", "Item")
                        .WithMany("TagLocations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RfidBarcode.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("RfidBarcode.Domain.Entities.Location", "PrevLocation")
                        .WithMany()
                        .HasForeignKey("PrevLocationId");

                    b.HasOne("RfidBarcode.Domain.Entities.StockOpname", "StockOpname")
                        .WithMany()
                        .HasForeignKey("StockOpnameId");

                    b.Navigation("Item");

                    b.Navigation("Location");

                    b.Navigation("PrevLocation");

                    b.Navigation("StockOpname");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.AccessMenu", b =>
                {
                    b.Navigation("AccessMenuRoles");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Gate", b =>
                {
                    b.Navigation("GateMaps");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Identities.ApplicationRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Identities.ApplicationUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Tokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Item", b =>
                {
                    b.Navigation("ItemMovements");

                    b.Navigation("ItemPrintLogs");

                    b.Navigation("StockOpnameDetails");

                    b.Navigation("TagLocations");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.Location", b =>
                {
                    b.Navigation("GateMapNext");

                    b.Navigation("GateMapPrev");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.StockOpname", b =>
                {
                    b.Navigation("StockOpnameDetails");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.SuratJalan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RfidBarcode.Domain.Entities.TrackingItem", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
